version: '3.7'

services:
  db:
    container_name: mireya_postgres
    image: 'postgres:16'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5432:5432'

  redis:
    container_name: mireya_redis
    image: redis
    ports:
      - '6379:6379'
    restart: always
